databases:
  - name: Deallio
    plan: free
    databaseName: Dealliodb
    user: Deallio

services:
  - type: web
    name: Deallio
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Deallio
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
